version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/laundry
      - EMAIL_USER=getnotifiedrightnow@gmail.com
      - EMAIL_PASS=lkrdlkqddwgfxasr
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: